services:
  - type: web
    name: n8n-service
    runtime: docker
    plan: free  # Can upgrade to 'starter' or 'standard' later
    branch: main  # Or your custom branch name
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://YOUR-SERVICE-NAME.onrender.com  # Update this after deployment
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Optional: Add basic authentication
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin  # Change this!
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true  # Render will generate a secure password

databases:
  - name: n8n-db
    databaseName: n8n
    plan: free  # Free tier expires after 90 days - upgrade to 'basic-256mb' for production
